/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    [path: `/api/tags/${number}`]: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get tag by ID
         * @description Retrieves a specific category tag by its ID.
         */
        get: operations["getTagById"];
        /**
         * Update an existing tag
         * @description Updates the details of an existing category tag by its ID.
         */
        put: operations["updateTag"];
        post?: never;
        /**
         * Delete a tag
         * @description Deletes an existing category tag by its ID.
         */
        delete: operations["deleteTag"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    [path: `/api/lectures/${number}`]: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get lecture by ID
         * @description Retrieves the details of a lecture by its ID.
         */
        get: operations["getLecture"];
        /**
         * Update an existing lecture
         * @description Updates the details of an existing lecture by its ID.
         */
        put: operations["updateLecture"];
        post?: never;
        /**
         * Delete a lecture
         * @description Deletes an existing lecture by its ID.
         */
        delete: operations["deleteLecture"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    [path: `/api/lectures/${number}/visit`]: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["visitLecture"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    [path: `/api/lectures/${number}/unparticipate`]: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Unconfirm participation in a lecture
         * @description Unconfirms the participation of the authenticated user in the specified lecture.
         */
        put: operations["unparticipate"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    [path: `/api/lectures/${number}/share`]: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["shareLecture"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    [path: `/api/lectures/${number}/participate`]: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Confirm participation in a lecture
         * @description Confirms the participation of the authenticated user in the specified lecture.
         */
        put: operations["participate"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    [path: `/api/lectures/${number}/image`]: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get lecture image details
         * @description Retrieves the JSON details of a lecture image by its ID.
         */
        get: operations["getLectureImage_1"];
        /**
         * Update lecture image
         * @description Updates the lecture image associated with the given lecture ID. Requires multipart file input.
         */
        put: operations["updateLectureImage"];
        post?: never;
        /**
         * Delete lecture image
         * @description Deletes the lecture image associated with the given lecture ID.
         */
        delete: operations["deleteLectureImage"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all tags
         * @description Retrieves a list of all category tags.
         */
        get: operations["getAllTags"];
        put?: never;
        /**
         * Create a new tag
         * @description Creates a new category tag with the provided details.
         */
        post: operations["createTag"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lectures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all lectures
         * @description Retrieves a list of all lectures. Optionally filter by user.
         */
        get: operations["getAllLectures"];
        put?: never;
        /**
         * Create a new lecture
         * @description Creates a new lecture with the provided details.
         */
        post: operations["createLecture"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    [path: `/api/lectures/${number}/comments`]: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAllLectureComments"];
        put?: never;
        post: operations["createComment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register a new user
         * @description Creates a new user account with the provided information. Returns the created user details.
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login a user
         * @description Authenticates a user with the provided credentials and returns a JWT token for access.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/send-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["sendEmail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get local host information
         * @description Returns the local host's address and other related information as a string.
         */
        get: operations["lecturizeIt"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get user details
         * @description Retrieves the details of the currently authenticated user.
         */
        get: operations["getUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/participating-lectures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get lectures the user is participating in
         * @description Retrieves a list of lectures that the currently authenticated user is participating in.
         */
        get: operations["getUserParticipatingLectures"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    [path: `/api/lectures/${number}/participants`]: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all participants of a lecture
         * @description Retrieves a list of all participants of the specified lecture.
         */
        get: operations["getAllLectureParticipants"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    [path: `/api/lectures/${number}/comments/${number}`]: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteComment"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Details of the tag to be created */
        TagInput: {
            name: string;
        };
        CategoryTag: {
            /** Format: int64 */
            id?: number;
            name?: string;
        };
        /** @description Lecture details for creation */
        LectureInput: {
            title: string;
            lecturer: string;
            description: string;
            /** Format: date-time */
            startsAt: string;
            /** Format: date-time */
            endsAt: string;
            type: string;
            url?: string;
            address?: string;
            /** Format: int32 */
            maximumCapacity?: number;
            tags?: components["schemas"]["TagIdInput"][];
        };
        TagIdInput: {
            /** Format: int64 */
            id: number;
        };
        LectureDTO: {
            id?: string;
            title?: string;
            lecturer?: string;
            description?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            startsAt?: string;
            /** Format: date-time */
            endsAt?: string;
            type?: string;
            status?: string;
            url?: string;
            address?: string;
            tags?: components["schemas"]["CategoryTag"][];
            /** Format: int32 */
            maximumCapacity?: number;
            organizer?: components["schemas"]["UserSummaryDTO"];
            metrics?: components["schemas"]["LectureMetricsDTO"];
        };
        LectureMetricsDTO: {
            /** Format: int32 */
            timesVisited?: number;
            /** Format: int32 */
            timesShared?: number;
        };
        UserSummaryDTO: {
            /** Format: int64 */
            id?: number;
            email?: string;
            username?: string;
        };
        /** @description Lecture image details for update */
        LectureImageInput: {
            /** Format: binary */
            file: string;
            description: string;
        };
        LectureImageDTO: {
            fileName?: string;
            description?: string;
            contentType?: string;
            /** Format: int64 */
            size?: number;
        };
        CommentInput: {
            text: string;
        };
        CommentDTO: {
            /** Format: int64 */
            id?: number;
            text?: string;
            user?: components["schemas"]["UserSummaryDTO"];
        };
        /** @description User details for registration */
        CreateUserInput: {
            email: string;
            username: string;
            password: string;
        };
        UserDTO: {
            /** Format: int64 */
            id?: number;
            username?: string;
            email?: string;
            roles?: string[];
        };
        /** @description User credentials for login */
        LoginInput: {
            email: string;
            password: string;
        };
        LoginDTO: {
            accessToken?: string;
            /** Format: int32 */
            expiresIn?: number;
        };
        LectureSummaryDTO: {
            /** Format: int64 */
            id?: number;
            title?: string;
            lecturer?: string;
            description?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            startsAt?: string;
            /** Format: date-time */
            endsAt?: string;
            type?: string;
            status?: string;
            tags?: string[];
            metrics?: components["schemas"]["LectureMetricsDTO"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getTagById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID of the category tag */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Category tag details retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CategoryTag"];
                };
            };
            /** @description Category tag not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CategoryTag"];
                };
            };
        };
    };
    updateTag: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID of the category tag to be updated */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagInput"];
            };
        };
        responses: {
            /** @description Category tag updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CategoryTag"];
                };
            };
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CategoryTag"];
                };
            };
            /** @description Invalid input, tag update failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CategoryTag"];
                };
            };
            /** @description Category tag not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CategoryTag"];
                };
            };
        };
    };
    deleteTag: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID of the category tag to be deleted */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Category tag deleted successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Category tag not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getLecture: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID of the lecture */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lecture details retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LectureDTO"];
                };
            };
            /** @description Lecture not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LectureDTO"];
                };
            };
        };
    };
    updateLecture: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID of the lecture to be updated */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LectureInput"];
            };
        };
        responses: {
            /** @description Lecture updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LectureDTO"];
                };
            };
            /** @description Invalid input or lecture update failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LectureDTO"];
                };
            };
            /** @description Lecture not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LectureDTO"];
                };
            };
        };
    };
    deleteLecture: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID of the lecture to be deleted */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lecture deleted successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Lecture not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    visitLecture: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    unparticipate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID of the lecture */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Participation unconfirmed successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized, user must be authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Lecture not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    shareLecture: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    participate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID of the lecture */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Participation confirmed successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized, user must be authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Lecture not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getLectureImage_1: {
        parameters: {
            query?: never;
            header: {
                /** @description Media type to accept */
                accept: string;
            };
            path: {
                /** @description ID of the lecture */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lecture image details retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
            /** @description Lecture image not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
            /** @description Requested media type not acceptable */
            406: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    updateLectureImage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID of the lecture */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["LectureImageInput"];
            };
        };
        responses: {
            /** @description Lecture image updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LectureImageDTO"];
                };
            };
            /** @description Invalid input or file format */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LectureImageDTO"];
                };
            };
            /** @description User is not authorized to update this lecture image */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LectureImageDTO"];
                };
            };
            /** @description Lecture or image not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LectureImageDTO"];
                };
            };
        };
    };
    deleteLectureImage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID of the lecture */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lecture image deleted successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User is not authorized to delete this lecture image */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Lecture or image not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getAllTags: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of category tags retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CategoryTag"][];
                };
            };
        };
    };
    createTag: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagInput"];
            };
        };
        responses: {
            /** @description Category tag created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CategoryTag"];
                };
            };
            /** @description Invalid input, tag creation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CategoryTag"];
                };
            };
        };
    };
    getAllLectures: {
        parameters: {
            query?: {
                /**
                 * @description Filter lectures by user
                 * @example john.doe@example.com
                 */
                user?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of lectures retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LectureSummaryDTO"][];
                };
            };
        };
    };
    createLecture: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LectureInput"];
            };
        };
        responses: {
            /** @description Lecture created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LectureDTO"];
                };
            };
            /** @description Invalid input, lecture creation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LectureDTO"];
                };
            };
        };
    };
    getAllLectureComments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lectureId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CommentDTO"][];
                };
            };
        };
    };
    createComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lectureId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommentInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CommentDTO"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserInput"];
            };
        };
        responses: {
            /** @description User created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserDTO"];
                };
            };
            /** @description Invalid input, user creation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserDTO"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginInput"];
            };
        };
        responses: {
            /** @description Login successful, JWT token returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LoginDTO"];
                };
            };
            /** @description Invalid credentials, login failed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LoginDTO"];
                };
            };
        };
    };
    sendEmail: {
        parameters: {
            query: {
                to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    lecturizeIt: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Local host information retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
            /** @description Internal server error due to host lookup failure */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    getUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User details retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserDTO"];
                };
            };
            /** @description Unauthorized, user must be authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserDTO"];
                };
            };
        };
    };
    getUserParticipatingLectures: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of participating lectures retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LectureSummaryDTO"][];
                };
            };
            /** @description Unauthorized, user must be authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LectureSummaryDTO"][];
                };
            };
        };
    };
    getAllLectureParticipants: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID of the lecture */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of lecture participants retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserSummaryDTO"][];
                };
            };
            /** @description Lecture not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserSummaryDTO"][];
                };
            };
        };
    };
    deleteComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                lectureId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
